blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/michallkanak/symfony-boilerplate/security/advisories/new
    about: Please report security vulnerabilities privately
